version: '3.6'
services:
  goalbox-server:
    container_name: goalbox-server
    build:
      dockerfile: ./goalbox-server/Dockerfile
      context: ./
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=goalbox-db
      - WEB3_CLIENT_HOST=member1
    healthcheck:
      test: 'curl --fail --silent localhost:8080/actuator/health || exit 1'
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      - goalbox-db
    networks:
      - goalbox
      - quorum-network
  goalbox-dapp:
    container_name: goalbox-dapp
    build:
      dockerfile: ./goalbox-dapp/Dockerfile
      context: ./
    ports:
      - '4000:80'
    healthcheck:
      test: service nginx status || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - goalbox
  goalbox-db:
    image: 'postgres:14.5'
    restart: on-failure
    container_name: goalbox-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goalbox
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./goalbox-db/.data/goalbox:/var/lib/postgresql/data
      - ./goalbox-db/goalbox-metadata-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - goalbox
networks:
  goalbox:
    driver: bridge
  quorum-network:
    external: true
